apiVersion: v1
kind: ConfigMap
metadata:
  name: executor-pod-template
  labels:
    {{- include "spark.labels" . | nindent 4 }}
data:
  executor-pod-template.yaml.template: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: spark-connect-kubernetes-executor
      labels:
        app.kubernetes.io/instance: {{ include "spark.name" . }}-executor
        {{ if .Values.mtls.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        spark-role: executor
        {{- with .Values.spark.executor.labels }}
        {{- toYaml . | nindent 16 }}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spark-kubernetes-executor
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.spark.executor.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.spark.executor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
