{{- $shouldCreateServiceAccount := .Values.serviceAccount.create -}}
{{- $resourceList := list "pods" "services" "configmaps" -}}
{{- $verbList := list "*" -}}

{{- if $shouldCreateServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark.fullname" . }}-role
  labels:
    {{- include "spark.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: {{ toJson $resourceList }}
  verbs: {{ toJson $verbList }}
{{- end }}