apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-properties
  labels:
    {{- include "spark.labels" . | nindent 4 }}
data:
  spark-properties.conf.template: |-
    spark.connect.grpc.binding.port {{ .Values.containerPorts.sparkConnect }}
    spark.decommission.enabled true
    spark.driver.cores {{ .Values.spark.driver.cores }}
    spark.driver.extraJavaOptions -XX:+ExitOnOutOfMemoryError -XX:+UseCompressedOops -XX:+UseZGC
    spark.executor.extraJavaOptions -XX:+UseZGC
    spark.driver.host ${SPARK_DRIVER_HOST}
    spark.driver.memory {{ .Values.spark.driver.memoryMiB }}m
    spark.driver.memoryOverhead {{ .Values.spark.driver.memoryOverheadMiB }}m
    {{- if .Values.spark.eventLog.enabled }}
    spark.eventLog.enabled true
    spark.eventLog.compress true
    spark.eventLog.compression.codecs zstd
    spark.eventLog.dir {{ .Values.spark.eventLog.dir }}
    spark.eventLog.logStageExecutorMetrics true
    spark.eventLog.logBlockUpdates.enabled true
    spark.eventLog.rolling.enabled true
    spark.eventLog.rolling.maxFileSize 128m
    {{- end }}
    spark.executor.cores {{ .Values.spark.executor.cores }}
    spark.executor.memory {{ .Values.spark.executor.memoryMiB }}m
    spark.executor.memoryOverhead {{ .Values.spark.executor.memoryOverheadMiB }}m
    spark.jars.ivy {{ .Values.spark.scratchDir }}/.ivy
    {{- with .Values.spark.packages }}
    spark.jars.packages {{ join "," . }}
    {{- end }}
    spark.local.dir {{ .Values.spark.scratchDir }}
    spark.master k8s://{{ .Values.spark.kubernetesEndpoint }}
    spark.network.timeout 300s
    spark.ui.port {{ .Values.containerPorts.sparkUi }}
    spark.ui.dagGraph.retainedRootRDDs 100
    spark.ui.retainedJobs 100
    spark.ui.retainedStages 100
    spark.ui.retainedTasks 100
    spark.worker.ui.retainedExecutors 100
    spark.worker.ui.retainedDrivers	10
    spark.sql.ui.retainedExecutions 100
    spark.streaming.ui.retainedBatches 100
    spark.ui.retainedDeadExecutors 10
    {{- if .Values.spark.celeborn.enabled }}
    spark.celeborn.master.endpoints  {{ .Values.spark.celeborn.masterEndpoints }}
    spark.shuffle.manager: org.apache.spark.shuffle.celeborn.SparkShuffleManager
    spark.shuffle.service.enabled false
    spark.executor.userClassPathFirst: false
    spark.celeborn.client.spark.shuffle.writer hash
    spark.celeborn.client.push.replicate.enabled true
    spark.sql.adaptive.localShuffleReader.enabled false
    spark.sql.adaptive.enabled true
    spark.sql.adaptive.skewJoin.enabled true
    spark.shuffle.sort.io.plugin.class org.apache.spark.shuffle.celeborn.CelebornShuffleDataIO
    spark.dynamicAllocation.shuffleTracking.enabled false
    {{- end }}
    {{- if .Values.spark.dynamicAllocation.enabled }}
    spark.dynamicAllocation.enabled true
    spark.dynamicAllocation.cachedExecutorIdleTimeout 600s
    spark.dynamicAllocation.executorAllocationRatio	1
    spark.dynamicAllocation.executorIdleTimeout	300s
    spark.dynamicAllocation.maxExecutors {{ .Values.spark.executor.maxExecutors }}
    spark.dynamicAllocation.minExecutors {{ .Values.spark.executor.minExecutors }}
    spark.dynamicAllocation.schedulerBacklogTimeout	1s
    spark.dynamicAllocation.sustainedSchedulerBacklogTimeout 5s
    {{- end }}
    {{ if not .Values.spark.celeborn.enabled }}
    spark.dynamicAllocation.shuffleTracking.enabled	true
    spark.dynamicAllocation.shuffleTracking.timeout	600s
    {{- end }}
    spark.kubernetes.allocation.driver.readinessTimeout 60s
    spark.kubernetes.authenticate.driver.serviceAccountName {{ include "spark.serviceAccountName" .  }}
    spark.kubernetes.authenticate.executor.serviceAccountName {{ include "spark.serviceAccountName" .  }}
    spark.kubernetes.authenticate.submission.caCertFile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    spark.kubernetes.authenticate.submission.oauthTokenFile /var/run/secrets/kubernetes.io/serviceaccount/token
    spark.kubernetes.container.image.pullPolicy {{ .Values.image.pullPolicy }}
    spark.kubernetes.driver.pod.name ${SPARK_DRIVER_POD_NAME}
    spark.kubernetes.executor.container.image {{ .Values.image.repository }}:{{ .Values.image.tag }}
    spark.kubernetes.executor.podTemplateFile /opt/spark/executor-pod-template.yaml
    spark.kubernetes.executor.request.cores {{ .Values.spark.executor.requestCoresMilliCPU }}m
    spark.kubernetes.local.dirs.tmpfs false
    spark.kubernetes.namespace {{ .Release.Namespace }}
    {{ if .Values.mtls.enabled }}
    spark.kubernetes.executor.service true
    spark.driver.bindAddress 0.0.0.0
    spark.driver.port 7078
    spark.blockManager.port 7079
    spark.executor.bindAddress 0.0.0.0
    spark.kubernetes.post.stop.script {{ .Values.mtls.poststopscript }}
    spark.kubernetes.pre.start.script {{ .Values.mtls.prestartscript }}
    {{- end }}
    {{- with .Values.spark.sparkConfig }}
    {{- range $key, $value := . }}
    {{ printf "%s %s" $key (toString $value) }}
    {{- end }}
    {{- end }}
